// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4l_gnqsJL6Xnnc45Mahg0Am57cw35T44',
    appId: '1:438978127745:web:d05009310c2d0a01ec2a80',
    messagingSenderId: '438978127745',
    projectId: 'aemo-loan-app',
    authDomain: 'aemo-loan-app.firebaseapp.com',
    storageBucket: 'aemo-loan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpJF9gEeG6QYxcsSj8rO6XZlGoP-ljbOI',
    appId: '1:438978127745:android:7e1b015faa992da5ec2a80',
    messagingSenderId: '438978127745',
    projectId: 'aemo-loan-app',
    storageBucket: 'aemo-loan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dZlYmXZFBtSqN3oWuYrE0IWA5_zCxSM',
    appId: '1:438978127745:ios:f32b38b8f39a26c6ec2a80',
    messagingSenderId: '438978127745',
    projectId: 'aemo-loan-app',
    storageBucket: 'aemo-loan-app.firebasestorage.app',
    iosBundleId: 'com.example.aemoloan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dZlYmXZFBtSqN3oWuYrE0IWA5_zCxSM',
    appId: '1:438978127745:ios:f32b38b8f39a26c6ec2a80',
    messagingSenderId: '438978127745',
    projectId: 'aemo-loan-app',
    storageBucket: 'aemo-loan-app.firebasestorage.app',
    iosBundleId: 'com.example.aemoloan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4l_gnqsJL6Xnnc45Mahg0Am57cw35T44',
    appId: '1:438978127745:web:51ea345bb668192aec2a80',
    messagingSenderId: '438978127745',
    projectId: 'aemo-loan-app',
    authDomain: 'aemo-loan-app.firebaseapp.com',
    storageBucket: 'aemo-loan-app.firebasestorage.app',
  );
}
